### ISSUE TITLE
conversion notebook - python cmds

### ISSUE THREAD

**Issue by pwalczysko** [ome/EMBL-EBI-imaging-course-05-2023#9]
![Screenshot 2023-05-19 at 14 24 15](https://github.com/ome/EMBL-EBI-imaging-course-05-2023/assets/2478303/8fc7e63f-3fff-41fb-8857-2b34df245ac8)

If the instruction is followed as written in the notebook, then, on the local terminal, I still get a problem, even when the conda env is activated.

```
(imaging_course_conversion_day5_2023) pwalczysko@Petrs-MBP EMBL-EBI-imaging-course-05-2023 % import os, shutil
zsh: command not found: import
```

I think this is because the ``import`` is a python command. What would work is to add 
``python`` as the first command and then run the import in the python terminal ?

**Comment by jburel** [comment]
Yes i will change that it does not make sense to use Python in middle to the terminal section

**Comment by jburel** [comment]
see 1bf3e099b8d95f3b3b96c964d6c894ff5390583d

**Comment by pwalczysko** [comment]
Sorry, the commit https://github.com/ome/EMBL-EBI-imaging-course-05-2023/commit/1bf3e099b8d95f3b3b96c964d6c894ff5390583d has the correct name, but the content is just fixing two commas - maybe a commit mixup ?
I also fetched freshly and rebuilt, and the desired ``rm -rf`` change is not there



![Screenshot 2023-05-19 at 15 49 08](https://github.com/ome/EMBL-EBI-imaging-course-05-2023/assets/2478303/818e94eb-5d73-4002-8d74-29a3f2e702fb)

**Comment by jburel** [comment]
Sorted this time https://github.com/ome/EMBL-EBI-imaging-course-05-2023/commit/cab048021e395b67dfe07c09dad27614963db973

**Comment by pwalczysko** [comment]
Yes, confirming, notebook works nicely now, thanks
